/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.156:34812'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.156:40990'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.156:36661'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.156:32974'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.156:41893'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.156:45972'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.156:45101'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.156:34728'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.156:41714'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.156:34761'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.156:34835'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.156:33565'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.156:46000'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.156:44580'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.156:36932'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.156:41260'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.156:38346'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.156:44935'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.156:39291'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.156:43076'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.156:39120'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.156:44928'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.156:45660'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.156:46731'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.156:46337'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.156:42196'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.156:38117'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.156:39132'
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.156:38795
distributed.worker - INFO -          Listening to:   tcp://172.30.5.156:38795
distributed.worker - INFO -              nanny at:         172.30.5.156:45101
distributed.worker - INFO -              bokeh at:         172.30.5.156:37807
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-o6ccrlax
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.156:35682
distributed.worker - INFO -          Listening to:   tcp://172.30.5.156:35682
distributed.worker - INFO -              nanny at:         172.30.5.156:44928
distributed.worker - INFO -              bokeh at:         172.30.5.156:44513
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-ity_vl5z
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.156:40373
distributed.worker - INFO -          Listening to:   tcp://172.30.5.156:40373
distributed.worker - INFO -              nanny at:         172.30.5.156:41893
distributed.worker - INFO -              bokeh at:         172.30.5.156:34881
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-vh3aruzg
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.156:43689
distributed.worker - INFO -          Listening to:   tcp://172.30.5.156:43689
distributed.worker - INFO -              nanny at:         172.30.5.156:45972
distributed.worker - INFO -              bokeh at:         172.30.5.156:42954
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-q9u558p2
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.156:39757
distributed.worker - INFO -          Listening to:   tcp://172.30.5.156:39757
distributed.worker - INFO -              nanny at:         172.30.5.156:46731
distributed.worker - INFO -              bokeh at:         172.30.5.156:38573
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-tfm5tiw_
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.156:42020
distributed.worker - INFO -          Listening to:   tcp://172.30.5.156:42020
distributed.worker - INFO -              nanny at:         172.30.5.156:33565
distributed.worker - INFO -              bokeh at:         172.30.5.156:37833
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-dn_f7tbx
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.156:37967
distributed.worker - INFO -          Listening to:   tcp://172.30.5.156:37967
distributed.worker - INFO -              nanny at:         172.30.5.156:42196
distributed.worker - INFO -              bokeh at:         172.30.5.156:33779
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-r449tit3
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.156:33151
distributed.worker - INFO -          Listening to:   tcp://172.30.5.156:33151
distributed.worker - INFO -              nanny at:         172.30.5.156:46000
distributed.worker - INFO -              bokeh at:         172.30.5.156:45607
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-s9pjjr4b
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.156:44003
distributed.worker - INFO -          Listening to:   tcp://172.30.5.156:44003
distributed.worker - INFO -              nanny at:         172.30.5.156:44935
distributed.worker - INFO -              bokeh at:         172.30.5.156:42975
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.156:41400
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -          Listening to:   tcp://172.30.5.156:41400
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -              nanny at:         172.30.5.156:38117
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-0cy_jaex
distributed.worker - INFO -              bokeh at:         172.30.5.156:45823
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-7r2k4qhm
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.156:42410
distributed.worker - INFO -          Listening to:   tcp://172.30.5.156:42410
distributed.worker - INFO -              nanny at:         172.30.5.156:39132
distributed.worker - INFO -              bokeh at:         172.30.5.156:41280
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.156:40237
distributed.worker - INFO -          Listening to:   tcp://172.30.5.156:40237
distributed.worker - INFO -              nanny at:         172.30.5.156:36932
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -              bokeh at:         172.30.5.156:45323
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-psnbiqy1
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-gpskeads
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.156:45417
distributed.worker - INFO -          Listening to:   tcp://172.30.5.156:45417
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -              nanny at:         172.30.5.156:34835
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              bokeh at:         172.30.5.156:33091
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.156:35593
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -          Listening to:   tcp://172.30.5.156:35593
distributed.core - INFO - Starting established connection
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -              nanny at:         172.30.5.156:45660
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -              bokeh at:         172.30.5.156:43322
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-w9v8jh23
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-nd3t4h77
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.156:45185
distributed.worker - INFO -          Listening to:   tcp://172.30.5.156:45185
distributed.worker - INFO -              nanny at:         172.30.5.156:40990
distributed.worker - INFO -              bokeh at:         172.30.5.156:45565
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-a7i00b9s
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.156:46158
distributed.worker - INFO -          Listening to:   tcp://172.30.5.156:46158
distributed.worker - INFO -              nanny at:         172.30.5.156:39291
distributed.worker - INFO -              bokeh at:         172.30.5.156:37464
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.156:41929
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -          Listening to:   tcp://172.30.5.156:41929
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -              nanny at:         172.30.5.156:36661
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              bokeh at:         172.30.5.156:41822
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-gbk2v4j8
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -               Threads:                          1
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.156:33675
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -          Listening to:   tcp://172.30.5.156:33675
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-t8jroyns
distributed.worker - INFO -              nanny at:         172.30.5.156:34812
distributed.worker - INFO -              bokeh at:         172.30.5.156:43478
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-13c5c6mn
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.156:46610
distributed.worker - INFO -          Listening to:   tcp://172.30.5.156:46610
distributed.worker - INFO -              nanny at:         172.30.5.156:32974
distributed.worker - INFO -              bokeh at:         172.30.5.156:43628
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-7etc_c6x
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.156:44046
distributed.worker - INFO -          Listening to:   tcp://172.30.5.156:44046
distributed.worker - INFO -              nanny at:         172.30.5.156:38346
distributed.worker - INFO -              bokeh at:         172.30.5.156:44534
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-g5hdnbno
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.156:34020
distributed.worker - INFO -          Listening to:   tcp://172.30.5.156:34020
distributed.worker - INFO -              nanny at:         172.30.5.156:43076
distributed.worker - INFO -              bokeh at:         172.30.5.156:43220
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-1hff9s97
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.156:41065
distributed.worker - INFO -          Listening to:   tcp://172.30.5.156:41065
distributed.worker - INFO -              nanny at:         172.30.5.156:41260
distributed.worker - INFO -              bokeh at:         172.30.5.156:34538
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-3rvn6ayq
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.156:43857
distributed.worker - INFO -          Listening to:   tcp://172.30.5.156:43857
distributed.worker - INFO -              nanny at:         172.30.5.156:46337
distributed.worker - INFO -              bokeh at:         172.30.5.156:33511
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-y_8uhw61
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.156:45205
distributed.worker - INFO -          Listening to:   tcp://172.30.5.156:45205
distributed.worker - INFO -              nanny at:         172.30.5.156:39120
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -              bokeh at:         172.30.5.156:34248
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.156:44976
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -          Listening to:   tcp://172.30.5.156:44976
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-qld0zb6a
distributed.worker - INFO -              nanny at:         172.30.5.156:44580
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              bokeh at:         172.30.5.156:37998
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-qcwsdrwz
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.156:43851
distributed.worker - INFO -          Listening to:   tcp://172.30.5.156:43851
distributed.worker - INFO -              nanny at:         172.30.5.156:34761
distributed.worker - INFO -              bokeh at:         172.30.5.156:33374
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-7qcpfjk4
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.156:44965
distributed.worker - INFO -          Listening to:   tcp://172.30.5.156:44965
distributed.worker - INFO -              nanny at:         172.30.5.156:34728
distributed.worker - INFO -              bokeh at:         172.30.5.156:44844
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-36n9249f
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.156:44012
distributed.worker - INFO -          Listening to:   tcp://172.30.5.156:44012
distributed.worker - INFO -              nanny at:         172.30.5.156:41714
distributed.worker - INFO -              bokeh at:         172.30.5.156:45986
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-kqgre12u
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56262 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56264 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56266 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56270 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56260 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56244 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56250 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56252 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56254 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56268 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56272 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56276 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56278 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56246 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56248 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56226 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56228 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56234 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56236 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56256 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56258 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56274 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56218 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56222 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56220 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56238 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56240 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56242 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56230 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56232 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:56224 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/array/numpy_compat.py:28: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:47424 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:47032 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:47036 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:46982 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/array/numpy_compat.py:28: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:47160 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:47162 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:47002 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:47112 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:47618 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:46990 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:47772 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:47420 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:47756 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:47714 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:46996 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48172 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:47458 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:47570 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48354 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:47906 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:47622 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48580 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48184 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:47460 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:47628 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48188 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:47908 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:47292 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48638 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48244 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48212 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/array/numpy_compat.py:28: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:47760 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48208 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48174 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48178 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:47624 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48578 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48182 remote=tcp://172.30.100.2:45385>
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b23f5086208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b23f5086208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b23f5086208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b23f5086208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b23f5086208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b23f5086208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b23f5086208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b23f5086208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b23f5086208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:47526 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48596 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:47528 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48210 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48768 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48614 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48388 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48576 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48458 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48204 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48584 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48594 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b23f5086208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b23f5086208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b23f5086208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48730 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49076 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48892 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49024 remote=tcp://172.30.100.2:45385>
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b23f5086208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b23f5086208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b23f5086208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b23f5086208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b23f5086208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b23f5086208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b23f5086208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b23f5086208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48728 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48732 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49196 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49268 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49204 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49276 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49194 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49262 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49266 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49202 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49248 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49274 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49254 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49284 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49316 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49322 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48438 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48046 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49264 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49328 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48978 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49034 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48216 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48326 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48382 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49176 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49236 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48514 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48556 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48666 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48776 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48844 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48038 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49260 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48973 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48154 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49028 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48324 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49166 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48434 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49226 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49346 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48659 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48774 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:47304 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49068 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48756 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:47920 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:47966 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49258 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49286 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48878 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48088 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48956 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48140 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49020 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48192 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48248 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48360 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49152 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49216 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48472 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49320 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48536 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48646 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48704 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48826 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48916 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49074 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48764 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:47922 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:47976 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48886 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48090 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48966 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48138 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49022 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48200 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48254 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48364 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49160 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:49220 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48546 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48650 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48702 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.156:48836 remote=tcp://172.30.100.2:45385>
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.utils_perf - INFO - full garbage collection released 11.93 MB from 8775 reference cycles (threshold: 10.00 MB)
distributed.utils_perf - INFO - full garbage collection released 15.52 MB from 8504 reference cycles (threshold: 10.00 MB)
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Stopping worker at tcp://172.30.5.156:40373
distributed.worker - INFO - Stopping worker at tcp://172.30.5.156:33151
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.156:41893'
distributed.worker - INFO - Stopping worker at tcp://172.30.5.156:43689
distributed.worker - INFO - Stopping worker at tcp://172.30.5.156:45185
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.156:46000'
distributed.worker - INFO - Stopping worker at tcp://172.30.5.156:42410
distributed.worker - INFO - Stopping worker at tcp://172.30.5.156:46158
distributed.worker - INFO - Stopping worker at tcp://172.30.5.156:41929
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.156:45972'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.156:40990'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.156:39132'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.156:39291'
distributed.worker - INFO - Stopping worker at tcp://172.30.5.156:41065
distributed.worker - INFO - Stopping worker at tcp://172.30.5.156:43851
distributed.worker - INFO - Stopping worker at tcp://172.30.5.156:39757
distributed.worker - INFO - Stopping worker at tcp://172.30.5.156:46610
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.156:36661'
distributed.worker - INFO - Stopping worker at tcp://172.30.5.156:35593
distributed.worker - INFO - Stopping worker at tcp://172.30.5.156:44003
distributed.worker - INFO - Stopping worker at tcp://172.30.5.156:41400
distributed.worker - INFO - Stopping worker at tcp://172.30.5.156:37967
distributed.worker - INFO - Stopping worker at tcp://172.30.5.156:38795
distributed.worker - INFO - Stopping worker at tcp://172.30.5.156:44046
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.156:41260'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.156:34761'
distributed.worker - INFO - Stopping worker at tcp://172.30.5.156:35682
distributed.worker - INFO - Stopping worker at tcp://172.30.5.156:45417
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.156:32974'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.156:44935'
distributed.worker - INFO - Stopping worker at tcp://172.30.5.156:40237
distributed.worker - INFO - Stopping worker at tcp://172.30.5.156:33675
distributed.worker - INFO - Stopping worker at tcp://172.30.5.156:42020
distributed.worker - INFO - Stopping worker at tcp://172.30.5.156:43857
distributed.worker - INFO - Stopping worker at tcp://172.30.5.156:34020
distributed.worker - INFO - Stopping worker at tcp://172.30.5.156:44976
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.156:38117'
distributed.worker - INFO - Stopping worker at tcp://172.30.5.156:44965
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.156:46731'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.156:38346'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.156:42196'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.156:45660'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.156:45101'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.156:44928'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.156:34835'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.156:36932'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.156:46337'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.156:34812'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.156:33565'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.156:43076'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.156:34728'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.156:44580'
distributed.worker - INFO - Stopping worker at tcp://172.30.5.156:45205
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.156:39120'
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Stopping worker at tcp://172.30.5.156:44012
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.156:41714'
distributed.dask_worker - INFO - End worker
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
