/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.177:44119'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.177:45244'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.177:42508'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.177:43467'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.177:46527'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.177:39532'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.177:41040'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.177:46414'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.177:46062'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.177:41566'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.177:46112'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.177:41536'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.177:37466'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.177:38792'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.177:38707'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.177:45810'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.177:36962'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.177:43665'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.177:37627'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.177:42769'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.177:43090'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.177:37948'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.177:41773'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.177:36978'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.177:46016'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.177:36905'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.177:34035'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.177:34516'
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.177:36694
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.177:41087
distributed.worker - INFO -          Listening to:   tcp://172.30.8.177:36694
distributed.worker - INFO -          Listening to:   tcp://172.30.8.177:41087
distributed.worker - INFO -              nanny at:         172.30.8.177:42508
distributed.worker - INFO -              nanny at:         172.30.8.177:38707
distributed.worker - INFO -              bokeh at:         172.30.8.177:33134
distributed.worker - INFO -              bokeh at:         172.30.8.177:37683
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-jidkgzyj
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-9cxiuwba
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.177:44652
distributed.worker - INFO -          Listening to:   tcp://172.30.8.177:44652
distributed.worker - INFO -              nanny at:         172.30.8.177:42769
distributed.worker - INFO -              bokeh at:         172.30.8.177:44828
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-6gqafioa
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.177:36163
distributed.worker - INFO -          Listening to:   tcp://172.30.8.177:36163
distributed.worker - INFO -              nanny at:         172.30.8.177:45244
distributed.worker - INFO -              bokeh at:         172.30.8.177:46685
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-ihqnsbmc
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.177:44620
distributed.worker - INFO -          Listening to:   tcp://172.30.8.177:44620
distributed.worker - INFO -              nanny at:         172.30.8.177:36978
distributed.worker - INFO -              bokeh at:         172.30.8.177:45638
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.177:33013
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.177:36411
distributed.worker - INFO -          Listening to:   tcp://172.30.8.177:33013
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -          Listening to:   tcp://172.30.8.177:36411
distributed.worker - INFO -              nanny at:         172.30.8.177:37466
distributed.worker - INFO -              nanny at:         172.30.8.177:43467
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -              bokeh at:         172.30.8.177:45438
distributed.worker - INFO -              bokeh at:         172.30.8.177:41338
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.177:44241
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-01si6n7y
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -          Listening to:   tcp://172.30.8.177:44241
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -              nanny at:         172.30.8.177:46414
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-21gybj2c
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-k0ejzgt8
distributed.worker - INFO -              bokeh at:         172.30.8.177:41604
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-86s5yjoj
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.177:42072
distributed.worker - INFO -          Listening to:   tcp://172.30.8.177:42072
distributed.worker - INFO -              nanny at:         172.30.8.177:41566
distributed.worker - INFO -              bokeh at:         172.30.8.177:37662
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-7mt9fxc3
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.177:46473
distributed.worker - INFO -          Listening to:   tcp://172.30.8.177:46473
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -              nanny at:         172.30.8.177:41773
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              bokeh at:         172.30.8.177:34540
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.177:37863
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -          Listening to:   tcp://172.30.8.177:37863
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              nanny at:         172.30.8.177:46527
distributed.core - INFO - Starting established connection
distributed.worker - INFO -              bokeh at:         172.30.8.177:41884
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-76z1osfe
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.core - INFO - Starting established connection
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-46bmpxbh
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.177:39141
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -          Listening to:   tcp://172.30.8.177:39141
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              nanny at:         172.30.8.177:41536
distributed.worker - INFO -              bokeh at:         172.30.8.177:39375
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-qhujdk71
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.177:36484
distributed.worker - INFO -          Listening to:   tcp://172.30.8.177:36484
distributed.worker - INFO -              nanny at:         172.30.8.177:46112
distributed.worker - INFO -              bokeh at:         172.30.8.177:45827
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-radync1i
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.177:40179
distributed.core - INFO - Starting established connection
distributed.worker - INFO -          Listening to:   tcp://172.30.8.177:40179
distributed.worker - INFO -              nanny at:         172.30.8.177:46016
distributed.worker - INFO -              bokeh at:         172.30.8.177:34946
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-x5d28ntx
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.177:43859
distributed.worker - INFO -          Listening to:   tcp://172.30.8.177:43859
distributed.worker - INFO -              nanny at:         172.30.8.177:38792
distributed.worker - INFO -              bokeh at:         172.30.8.177:44213
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-mz1no3mj
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.177:39877
distributed.worker - INFO -          Listening to:   tcp://172.30.8.177:39877
distributed.worker - INFO -              nanny at:         172.30.8.177:34035
distributed.worker - INFO -              bokeh at:         172.30.8.177:42987
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-uj4_mqj3
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.177:46614
distributed.worker - INFO -          Listening to:   tcp://172.30.8.177:46614
distributed.worker - INFO -              nanny at:         172.30.8.177:37948
distributed.worker - INFO -              bokeh at:         172.30.8.177:38528
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-ljvidvul
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.177:39915
distributed.worker - INFO -          Listening to:   tcp://172.30.8.177:39915
distributed.worker - INFO -              nanny at:         172.30.8.177:36905
distributed.worker - INFO -              bokeh at:         172.30.8.177:36030
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-zjba81bm
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.177:44072
distributed.worker - INFO -          Listening to:   tcp://172.30.8.177:44072
distributed.worker - INFO -              nanny at:         172.30.8.177:39532
distributed.worker - INFO -              bokeh at:         172.30.8.177:43623
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-fnf6y5vv
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.177:46417
distributed.worker - INFO -          Listening to:   tcp://172.30.8.177:46417
distributed.worker - INFO -              nanny at:         172.30.8.177:41040
distributed.worker - INFO -              bokeh at:         172.30.8.177:44833
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.177:44277
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO -          Listening to:   tcp://172.30.8.177:44277
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              nanny at:         172.30.8.177:46062
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -              bokeh at:         172.30.8.177:43590
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-bghju2zd
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.177:35045
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -          Listening to:   tcp://172.30.8.177:35045
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-020vfw5y
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              nanny at:         172.30.8.177:34516
distributed.worker - INFO -              bokeh at:         172.30.8.177:40788
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-mjuia3nd
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.177:33750
distributed.worker - INFO -          Listening to:   tcp://172.30.8.177:33750
distributed.worker - INFO -              nanny at:         172.30.8.177:43090
distributed.worker - INFO -              bokeh at:         172.30.8.177:43966
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-fllfkndn
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.177:37353
distributed.worker - INFO -          Listening to:   tcp://172.30.8.177:37353
distributed.worker - INFO -              nanny at:         172.30.8.177:36962
distributed.worker - INFO -              bokeh at:         172.30.8.177:41761
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.177:45676
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-jgfjuwoa
distributed.worker - INFO -          Listening to:   tcp://172.30.8.177:45676
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              nanny at:         172.30.8.177:44119
distributed.worker - INFO -              bokeh at:         172.30.8.177:45733
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-b27wo6b_
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.177:38553
distributed.worker - INFO -          Listening to:   tcp://172.30.8.177:38553
distributed.worker - INFO -              nanny at:         172.30.8.177:43665
distributed.worker - INFO -              bokeh at:         172.30.8.177:38666
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-pkc7ziq3
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.177:38105
distributed.worker - INFO -          Listening to:   tcp://172.30.8.177:38105
distributed.worker - INFO -              nanny at:         172.30.8.177:37627
distributed.worker - INFO -              bokeh at:         172.30.8.177:33291
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-m6t2rijx
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.177:37384
distributed.worker - INFO -          Listening to:   tcp://172.30.8.177:37384
distributed.worker - INFO -              nanny at:         172.30.8.177:45810
distributed.worker - INFO -              bokeh at:         172.30.8.177:35765
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-0r9hu50p
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:44088 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:44086 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:44096 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:44100 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:44098 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:44062 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:44060 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:44080 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:44082 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:44084 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:44076 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:44074 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:44078 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:44064 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:44066 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:44046 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:44050 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:44048 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:44070 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:44068 remote=tcp://172.30.5.156:33675>
distributed.utils_perf - INFO - full garbage collection released 26.33 MB from 524 reference cycles (threshold: 10.00 MB)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.utils_perf - INFO - full garbage collection released 28.78 MB from 1384 reference cycles (threshold: 10.00 MB)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:59112 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:59542 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:44073 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:44092 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:44090 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:44094 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:59656 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60156 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:59654 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60158 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:59658 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60154 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:59998 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60310 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/array/numpy_compat.py:28: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:59354 remote=tcp://172.30.100.2:45385>
distributed.utils_perf - INFO - full garbage collection released 74.84 MB from 1896 reference cycles (threshold: 10.00 MB)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:59358 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:59416 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60742 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:59360 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:59406 remote=tcp://172.30.100.2:45385>
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ac4d1120208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ac4d1120208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ac4d1120208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ac4d1120208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ac4d1120208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ac4d1120208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ac4d1120208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ac4d1120208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ac4d1120208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60758 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60744 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60966 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:44052 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:59866 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60946 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:44056 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:44054 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:44058 remote=tcp://172.30.5.156:33675>
distributed.utils_perf - INFO - full garbage collection released 74.78 MB from 1050 reference cycles (threshold: 10.00 MB)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:59876 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60098 remote=tcp://172.30.100.2:45385>
distributed.utils_perf - INFO - full garbage collection released 74.87 MB from 848 reference cycles (threshold: 10.00 MB)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ac4d1120208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ac4d1120208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ac4d1120208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ac4d1120208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ac4d1120208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ac4d1120208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ac4d1120208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ac4d1120208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ac4d1120208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60944 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:59352 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33028 remote=tcp://172.30.100.2:45385>
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ac4d1120208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ac4d1120208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ac4d1120208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ac4d1120208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ac4d1120208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ac4d1120208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ac4d1120208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ac4d1120208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ac4d1120208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33496 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33135 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60540 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33466 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33532 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33464 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33528 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33634 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60296 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60072 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33068 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60466 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33468 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33112 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33206 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33264 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60688 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33318 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33376 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60798 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60912 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:32788 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:32900 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:32956 remote=tcp://172.30.100.2:45385>
distributed.utils_perf - INFO - full garbage collection released 74.91 MB from 2055 reference cycles (threshold: 10.00 MB)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60208 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60096 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33502 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33136 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60548 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33290 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33346 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60770 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60828 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60882 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33428 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33436 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60940 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60992 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33556 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:32822 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:32872 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:32928 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:32982 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33036 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33096 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33230 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:59792 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33064 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60460 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60516 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33260 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60682 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60740 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33372 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60796 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60906 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60962 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:32784 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:32842 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:32894 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:32952 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33146 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33184 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33315 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33599 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33368 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60458 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33110 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60514 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33182 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60624 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33256 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60680 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33312 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60736 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33654 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60792 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60904 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:32838 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:32892 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:32948 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33676 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33004 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33060 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33462 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33498 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33138 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60542 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33212 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33286 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33342 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60766 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33396 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60822 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60880 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33438 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60934 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60990 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33554 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:32824 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:32866 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:32922 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:32980 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33034 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33090 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33234 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33590 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33284 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60708 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33340 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60764 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33394 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60820 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60876 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60932 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33486 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60988 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33552 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:32864 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:32920 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:32976 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33032 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33088 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33164 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33228 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33522 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60566 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33574 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33204 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33364 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60788 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33406 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60844 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60892 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60948 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:32780 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:32806 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33632 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:32836 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:32890 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:32946 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33000 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33058 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33104 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33308 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33582 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33470 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33270 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60690 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33322 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60748 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60860 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:60974 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33542 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:32854 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:32908 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33662 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:32960 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33074 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33116 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33154 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33198 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.177:33384 remote=tcp://172.30.100.2:45385>
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Stopping worker at tcp://172.30.8.177:37384
distributed.worker - INFO - Stopping worker at tcp://172.30.8.177:44277
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.177:45810'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.177:35045
distributed.worker - INFO - Stopping worker at tcp://172.30.8.177:43859
distributed.worker - INFO - Stopping worker at tcp://172.30.8.177:39915
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.177:46062'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.177:33013
distributed.worker - INFO - Stopping worker at tcp://172.30.8.177:36694
distributed.worker - INFO - Stopping worker at tcp://172.30.8.177:44072
distributed.worker - INFO - Stopping worker at tcp://172.30.8.177:38553
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.177:34516'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.177:37863
distributed.worker - INFO - Stopping worker at tcp://172.30.8.177:44652
distributed.worker - INFO - Stopping worker at tcp://172.30.8.177:46614
distributed.worker - INFO - Stopping worker at tcp://172.30.8.177:36411
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.177:36905'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.177:38792'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.177:45676
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.177:37466'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.177:36484
distributed.worker - INFO - Stopping worker at tcp://172.30.8.177:39141
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.177:39532'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.177:42508'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.177:43665'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.177:41087
distributed.worker - INFO - Stopping worker at tcp://172.30.8.177:39877
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.177:37948'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.177:46417
distributed.worker - INFO - Stopping worker at tcp://172.30.8.177:33750
distributed.worker - INFO - Stopping worker at tcp://172.30.8.177:38105
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.177:43467'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.177:44620
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.177:46527'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.177:44119'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.177:46473
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.177:42769'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.177:40179
distributed.worker - INFO - Stopping worker at tcp://172.30.8.177:42072
distributed.worker - INFO - Stopping worker at tcp://172.30.8.177:44241
distributed.worker - INFO - Stopping worker at tcp://172.30.8.177:37353
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.177:46112'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.177:34035'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.177:41536'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.177:38707'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.177:43090'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.177:41040'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.177:37627'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.177:36978'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.177:41773'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.177:46016'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.177:41566'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.177:46414'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.177:36962'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.177:36163
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.177:45244'
distributed.dask_worker - INFO - End worker
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
